/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 skincare.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/skincare.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Material} position={[-0.104, 1.208, -0.149]} rotation={[-0.454, -0.943, -0.276]} scale={0.816} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.003']} position={[0.169, 2.814, -0.514]} rotation={[-0.454, -0.943, -0.276]} scale={[0.522, 0.522, 0.56]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.004']} position={[-0.104, 1.208, -0.149]} rotation={[-0.454, -0.943, -0.276]} scale={[0.174, 0.729, 0.181]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.005']} position={[-0.104, 1.208, -0.149]} rotation={[-0.454, -0.943, -0.276]} scale={0.687} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.006']} position={[-0.104, 1.208, -0.149]} rotation={[-0.454, -0.943, -0.276]} scale={0.687} />
    </group>
  )
}

useGLTF.preload('/skincare.gltf')
